@extends('layouts.app')
@section('meta')
    @include('components.meta')
@endsection
@section('topbanner')
	@include('components.topbanner')
@endsection
@section('navbar')
	@include('components.navbar')
@endsection
@section('content')
	@include('components.about-content')
@endsection
@section('footer')
    @include('components.footer')
@endsection
@section('scripts')
    @include('components.scripts')
@endsection
