insert into tours (title, link, category, summary,detail) VALUES 
	("Deosai", "deosai", "safari", "The Deosai National Park is a high-altitude alpine plain (plateau) and national park in the Skardu Valley, Northern Pakistan region of Gilgit-Baltistan.

Deosai Plains are situated at an average elevation of 4,114 metres (13,497 ft) above sea level and considered as the second highest plateaus in the world.

", "Deosai is accessible from Skardu District in the north, Galtari Kharmang District in the south-east and the Astore District in the west. It is also accessible from Mehdiabad via Mehdiabad-Dapa Road. Deosai is located approximately 30 km from Skardu city, which is the shortest route to visit Deosai. Another route is from Astore valley via Chilim. It is also accessible from Shila valley. The people of Galtari travel via Deosai. While it is a National Park, the Gujjar-Bakwarwal travel large distances to utilize the Deosai National Park as grazing lands. There is another route called Burgi la via Tsoq Kachura valley Skardu.

The Deosai Plains are also home to the Siberian ibex, Snow Leopard, Kashmir Musk Deer, Himalayan wolf, Himalayan marmot and over 124 types of resident and migratory birds. Birds in the park include the Golden eagle, Lammergeier, Himalayan vulture, Laggar falcon, Peregrine falcon, Eurasian kestrel, Eurasian sparrowhawk, and Himalayan snowcock.

"),
	("Astore", "astore", "safari", "The Astore Valley has an area of 5,092 km² and is at an altitude of 2,600 metres (8,500 ft). The valley has approximately 250 square kilometres (97 sq mi) of glacier cover. The nearest glacier after entering the valley is the Harcho Glacier and the most accessible glacier is the Siachen Glacier." , "In the past, due to rough modes of transportation, there were some negative perceptions about travel in the Astore Valley, but nowadays there are paved roads connecting Islamabad and Gilgit by way of the Karakoram Highway. However, landslides and rockfall may still be issues in some areas of the Indus Valley. There is a permanent road to Gilgit, as well as seasonal road access to Skardu via the Deosai Plateau. It's now possible to obtain several types of vehicles (jeeps, SUVs, taxis, and wagons) and to hire jeeps and SUVs at affordable prices. The most used vehicles are jeeps and SUVs, with a local preference for Pajeros and Landcruisers.

"),
	("Sarfaranga", "sarfaranga", "safari" ,"Gilgit Baltistan is perhaps, the most spectacular region of Pakistan in terms of its geography and scenic beauty. The Cold Desert located in sarfaranga village in Skardu, Gilgit-Baltistan is the world's highest desert with an altitude of almost 1000 feet.
", "Gilgit Baltistan is perhaps, the most spectacular region of Pakistan in terms of its geography and scenic beauty. The Cold Desert located in sarfaranga village in Skardu, Gilgit-Baltistan is the world’s highest desert with an altitude of almost 1000 feet. The Skardu desert is enclosed by a valley and covered with lush green vegetation at the confluence of the Indus and also the Shigar Rivers. The distinctive quality of this desert is that it’s a cold desert with sturdy winds bashing the sand dunes. Its sand is white, granular and very fine which is a beautiful surprise itself. Its mesmerizing cold nights and splendid sandy view holds a strange attraction.

"),
	("Balochistan", "balochistan", "safari", "Balochistan is one of the four provinces of Pakistan. It is the largest province in terms of land area, forming the southwestern region of the country, but is the least populated. Its provincial capital and largest city is Quetta.

", "Balochistan is situated in the southwest of Pakistan and covers an area of 347,190 square kilometres (134,050 sq mi). It is Pakistan's largest province by area, constituting 44% of Pakistan's total land mass. The province is bordered by Afghanistan to the north and north-west, Iran to the south-west, Punjab and Sindh, and Khyber Pakhtunkhwa and the Federally Administered Tribal Areas to the north-east. To the south lies the Arabian Sea. Balochistan is located on the south-eastern part of the Iranian plateau. It borders the geopolitical regions of the Middle East and Southwest Asia, Central Asia and South Asia. Balochistan lies at the mouth of the Strait of Hormuz and provides the shortest route from seaports to Central Asia. Its geographical location has placed the otherwise desolate region in the scope of competing for global interests for all of recorded history.

The capital city Quetta is located in a densely populated portion of the Sulaiman Mountains in the north-east of the province. It is situated in a river valley near the Bolan Pass, which has been used as the route of choice from the coast to Central Asia, entering through Afghanistan's Kandahar region. The British and other historic empires have crossed the region to invade Afghanistan by this route.

Balochistan is rich in exhaustible and renewable resources; it is the second major supplier of natural gas in Pakistan. The province's renewable and human resource potential has not been systematically measured or exploited due to pressures from within and without Pakistan. Local inhabitants have chosen to live in towns and have relied on sustainable water sources for thousands of years.")